version: "3.4"
services:
  nido-api:
    build:
      context: .
      target: nido-api
    ports:
      - "80:80"
    environment:
      - FLASK_APP=nido.web
      - FLASK_DEBUG=TRUE
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=80
      - NIDO_DEBUG=""
      - NIDOD_RPC_HOST=nido-supervisor
      - NIDOD_MQTT_HOSTNAME=mosquitto
    volumes:
      - ./config:/app/nido/instance
      - ./package:/app/nido
    entrypoint:
      - flask
      - run
      - --without-threads
  nido-supervisor:
    build:
      context: .
      target: nido-supervisor
    environment:
      - NIDO_TESTING_GPIO=/tmp/gpio_pins.yaml
      - NIDO_TESTING=""
      - NIDOD_MQTT_HOSTNAME=mosquitto
    volumes:
      - ./instance:/app/instance
      - ./log:/app/log
      - ./package:/app/nido
  mosquitto:
    build:
      context: .
      target: nido-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./log:/mosquitto/log
      - ./instance:/mosquitto/data
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    volumes:
      - ./config/homebridge:/homebridge
      - ./homebridge-nido:/homebridge-nido
    environment:
      - TZ=America/Los_Angeles
    ports:
      - "8080:8080"
