version: "3.4"
services:
  nido-api:
    build:
      context: .
      target: nido-api
    restart: always
    ports:
      - "80:80"
    environment:
      - NIDOD_RPC_HOST=nido-supervisor
      - NIDOD_MQTT_HOSTNAME=mosquitto
  nido-supervisor:
    build:
      context: .
      target: nido-supervisor
    restart: always
    environment:
      - NIDOD_MQTT_HOSTNAME=mosquitto
    privileged: true
    volumes:
      - ./instance:/app/instance
      - ./log:/app/log
  mosquitto:
    build:
      context: .
      target: nido-mqtt
    user: "USER:GROUP"
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./log:/mosquitto/log
      - ./instance:/mosquitto/data
  homebridge:
    image: oznu/homebridge:arm32v6
    restart: always
    network_mode: host
    environment:
      - PUID=USER
      - PGID=GROUP
    volumes:
      - ./homebridge:/homebridge
    environment:
      - TZ=UTC
